name: Generate java transitive dependency graph
on:
  push:
    branches:
      - "master"
  
permissions:
  contents: write

jobs:
  generate-dependency-graph:
    uses: govuk-pay/pay-ci/.github/workflows/_run-java-transitive-dependency-update.yml@c1bed255fa76164f86f2b0f0f20df26ea58ab1c6